name: Publish to PyPI
on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.9

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry

      - name: Get release version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Check version consistency
        run: |
          PYPROJECT_VERSION=$(poetry version -s)
          RELEASE_VERSION=${{ steps.get_version.outputs.VERSION }}
          if [ "v$PYPROJECT_VERSION" != "$RELEASE_VERSION" ]; then
            echo "Error: Version mismatch. pyproject.toml version ($PYPROJECT_VERSION) does not match release tag ($RELEASE_VERSION)"
            exit 1
          fi

      - name: Build and publish
        run: |
          poetry build
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish